language: go
notifications:
  email:
  - cf-lamb@pivotallabs.com

before_install:
- go get code.google.com/p/go.tools/cmd/cover
- go get code.google.com/p/go.tools/cmd/vet
- go get github.com/mattn/goveralls
- go get github.com/onsi/ginkgo/ginkgo
- go install github.com/coreos/etcd

after_success:
- 'echo "mode: set" > all.coverprofile'
- 'find . -name "*.coverprofile" -exec grep -v mode: {} >> all.coverprofile \;'
- PATH=$HOME/gopath/bin:$PATH goveralls -coverprofile=all.coverprofile -repotoken=$COVERALLS_TOKEN

install:
- go get -d -v -t ./...

script:
- go vet ./...
- go test -bench . -run=Benchmark -v ./...
- PATH=$HOME/gopath/bin:$PATH ginkgo -r --race --randomizeAllSpecs --failOnPending --skipMeasurements --cover

go:
- 1.2.1

env:
  global:
    secure: V9bjpHgZ0zAHq9KJmPsa13EKqN1mn2N9oEIN2KQlD9JPWj4kR9gZ4JKiiq9ju5U4ZREbXq2VfLkXutvWfqeaczo9Dl2yB/qnkcl77DIbPJyEFXxON07oGkRALJMaK7ROp/+8hG6ZgfOcvc1BF2Kg7S9sRKYun2C2zUc0fSfUAY4=
